version: '3.3'

services:
  api:
    image: timoa/nodejs-encryption-api-example:latest@sha256:33cac806d192b0c025adb464d0dae158785b13ade8826a34ca4d08a8f6a19b61
    environment:
      - NODE_ENV=production
      - NODE_HOST=0.0.0.0
      - MONGO_HOST=mongo
      - WAIT_HOSTS=mongo:27017
    ports:
      - 3000:3000
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo@sha256:c57e511ce78d6847e2605db8e374611492f588e24f93c80e0c6baba9d6c029c3
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:27017"]
        interval: 30s
        timeout: 10s
        retries: 5
