name: Code Review

on: [pull_request]

jobs:

  # -- DOCKER -----------------------------------------------------------------
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      - name: Run hadolint
        uses: reviewdog/action-hadolint@9ab0e438e4266f368e1a782cee6b85a404b2d6a0 # tag=v1.32.1
