name: Code Review

on: [pull_request]

jobs:

  # -- DOCKER -----------------------------------------------------------------
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      - name: Run hadolint
        uses: reviewdog/action-hadolint@0e7a869dbe1c30ca2b3facbc9067148187e9ab5a # tag=v1.32.0
